
# Site settings
title: Project-ceti
email:
description: > # this means to ignore newlines until "baseurl:"
 
url: " " # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
gems: []

markdown: 
# toc_levels: 1..2
#https://www.youtube.com/watch?v=ChNBXRjHDnE