
# Site settings
title: Project-ceti
email:
description:  # this means to ignore newlines until "baseurl:" 
url: https://alberth7.github.io/

# User setting
owner:
email: "maikeru.bash@gmail.com"
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
gems: []

markdown: 
# toc_levels: 1..2
#https://www.youtube.com/watch?v=ChNBXRjHDnE
